export const routes = {
  home: "/",
  leistungen: "/leistungen",
  arbeitsmedizin: "/leistungen/arbeitsmedizin",
  arbeitssicherheit: "/leistungen/arbeitssicherheit",
  bahnmedizin: "/leistungen/bahnmedizin",
  impfungen: "/leistungen/impfungen",
  digitaleProzesse: "/leistungen#digitale-prozesse",
  gesundheitsmanagement: "/leistungen#gesundheitsmanagement",
  betriebsarztMuenchen: "/betriebsarzt-muenchen",
  fuerUnternehmen: "/fuer-unternehmen",
  betreuungsbedarf: "/betreuungsbedarf",
  rueckruf: "/rueckruf",
  faq: "/faq",
  kontakt: "/kontakt",
  impressum: "/impressum",
  datenschutz: "/impressum#datenschutz",
  leitung: "/#leitung",
  homeFaq: "/#faq",
} as const;
